### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Couldn't load tehreerjni from loader

### ISSUE THREAD

**Issue by KarsonKimbrel** [mta452/Tehreer-Android#9]
Hello I am currently upgrading my app from 2.0 to 2.1 of your library to fix the issues with Android 4.x.

At this line I am getting an UnsatisfiedLinkError:
`tehreerTypeface = new com.mta.tehreer.graphics.Typeface(context.getAssets(), "fonts/font.ttf");`

The Exception:
```
java.lang.UnsatisfiedLinkError: Couldn't load tehreerjni from loader dalvik.system.PathClassLoader[dexPath=/data/app/com.jesusfilmmedia.android.jesusfilm-1.apk,libraryPath=/data/app-lib/com.jesusfilmmedia.android.jesusfilm-1]: findLibrary returned null
        at java.lang.Runtime.loadLibrary(Runtime.java:355)
        at java.lang.System.loadLibrary(System.java:525)
        at com.mta.tehreer.internal.JniBridge.loadLibrary(JniBridge.java:27)
        at com.mta.tehreer.graphics.Typeface.<clinit>(Typeface.java:39)
        ...
```

This does not appear to be an issue on my Pixel (8.1), but it is an issue on my SamsungGalaxy S4 (Android 4.3)

Please let me know if I am doing something wrong or if I need to wait for this to be fixed on your side.

**Comment by mta452** [comment]
It looks like some architectures got missed in the release. I have re-uploaded the `aar` file. Please download the library again and hopefully, the issue will be resolved.

**Comment by KarsonKimbrel** [comment]
Thanks for the quick response, I'll try it out tomorrow when I have access to the device.

**Comment by mta452** [comment]
Sure, let me know how it goes.

**Comment by KarsonKimbrel** [comment]
I can confirm that this issue has been fixed. Thank you.
